### PR TITLE
Improve protection

### PR DESCRIPTION
**Pull request by AAA-ALR**
Add invalid object, player model switch

### CODE REVIEW

**Comment by AAA-ALR** [comment]
Player death model switching in RDO not getting fixed by rockstar

**Comment by AAA-ALR** [comment]
Switch to animal death and then switch again

> How does this crash work? Blocking all non-MP models does not seem to be the solution

**Comment by AAA-ALR** [comment]
Fish and birds, these two animals

**Comment by AAA-ALR** [comment]
I originally wanted to try hook the solution   I think it’s better to prioritize hooking. But at least your idea is better than mine

**Comment by gir489returns** [comment]
> How does this crash work? Blocking all non-MP models does not seem to be the solution

There are legit scenarios where the game switches your model to animals, during the Harriet hallucinations, for example. However, I do not think other players can see you as the animal.

**Pull request merged**
