### PR TITLE
Add Vulkan API Support

### PR DESCRIPTION
**Pull request by Hydra-Source**
It's unfinished in the current state but it will work fine. I forced unload when resizing due to the logic how Vulkan works. This can be fixed very easily with some time. You'd need to re-hook the Vulkan functions from the fresh created "Fake Device" in renderer init. The code is in unfinished state so you might catch a few weird things. ;P

### CODE REVIEW

**Comment by Hydra-Source** [comment]
I will also be away for a day or two so edit as you wish.

**Comment by tim-gromeyer** [comment]
When I inject it before loading into story/online it Freezes my Game and when injecting it in online, it Crashes my Game :/

https://github.com/YimMenu/HorseMenu/assets/58736434/dbba9d76-9382-4cf6-b74a-26df0d162ac9

**Comment by Hydra-Source** [comment]
> When I inject it before loading into story/online it Freezes my Game and when injecting it in online, it Crashes my Game :/
> 
> 
> 
> https://github.com/YimMenu/HorseMenu/assets/58736434/dbba9d76-9382-4cf6-b74a-26df0d162ac9
> 
> 
> 
> 

Was not tested on Linux. There might be windows specific stuff inside the code. Did not pay attention really. Will check it.

**Comment by Hydra-Source** [comment]
> When I inject it before loading into story/online it Freezes my Game and when injecting it in online, it Crashes my Game :/
> 
> 
> 
> https://github.com/YimMenu/HorseMenu/assets/58736434/dbba9d76-9382-4cf6-b74a-26df0d162ac9
> 
> 
> 
> 

Not tested in Linux. Will check.

**Comment by tim-gromeyer** [comment]
> Was not tested on Linux.

I can test it, we can get in touch and I will test it before you commit.

> There might be windows specific stuff inside the code. Did not pay attention really

Windows specific stuff **should** be fine, since Wine/Proton will translate it into something Linux/Unix specific. When it comes to Vulkan, it passes it directly to the GPU without translating anything. Idk if this matters

> Will check it

Perfect, thank you!

**Comment by Hydra-Source** [comment]
> > Was not tested on Linux.
> 
> 
> 
> I can test it, we can get in touch and I will test it before you commit.
> 
> 
> 
> > There might be windows specific stuff inside the code. Did not pay attention really
> 
> 
> 
> Windows specific stuff **should** be fine, since Wine/Proton will translate it into something Linux/Unix specific. When it comes to Vulkan, it passes it directly to the GPU without translating anything. Idk if this matters
> 
> 
> 
> > Will check it
> 
> 
> 
> Perfect, thank you!
> 
> 

Hey, do you have 2 GPU's? (APU(CPU integrated), GPU)

**Comment by tim-gromeyer** [comment]
> Hey, do you have 2 GPU's? (APU(CPU integrated), GPU)

Yeah, I have a Intel Core i5 11300H with integrated GPU (APU) and a Nvidia RTX 3050ti mobile

**Comment by Hydra-Source** [comment]
> > Hey, do you have 2 GPU's? (APU(CPU integrated), GPU)
> 
> 
> 
> Yeah, I have a Intel Core i5 11300H with integrated GPU (APU) and a Nvidia RTX 3050ti mobile
> 
> 

Alright, i might have an idea on whats going on then. It is probably a bug in getting the correct GPU. Although it's merely a guess. As i'm not home currently i cannot say for sure but i will definitely look at it tomorrow. Also i might need you for test purposes if thats fine. Contact me on discord: marcezsa

**Comment by Hydra-Source** [comment]
> This works for me. I do see some render artifacts when I move the window around but the game doesn't crash every five minutes anymore. Well done

Good to hear. What type of artifacts?

**Comment by Hydra-Source** [comment]
> This works for me. I do see some render artifacts when I move the window around but the game doesn't crash every five minutes anymore. Well done

Do you use HDR? If so turn it off. Or try toggling it in general. I noticed it's display color related. And also if your over-resizing your window in fullscreen. To sum it up it's a issue due to color in fullscreen as of my testing.

**Comment by Hydra-Source** [comment]
Ready for testing and merging if success.

**Comment by Hydra-Source** [comment]
> > > This works for me. I do see some render artifacts when I move the window around but the game doesn't crash every five minutes anymore. Well done
> 
> > 
> 
> > Do you use HDR? If so turn it off. Or try toggling it in general. I noticed it's display color related. And also if your over-resizing your window in fullscreen. To sum it up it's a issue due to color in fullscreen as of my testing.
> 
> 
> 
> HDR is disabled
> 
> 
> 
> > Good to hear. What type of artifacts?
> 
> 
> 
> A small white square near the left edge of the screen

Different artefact then what i experienced then. Mind sending a screenshot?

**Pull request merged**
