### PR TITLE
Change explosion method

### PR DESCRIPTION
**Pull request by Rxann**
Change the explosion method so you cannot see that the user blew someone up, instead it shows they just died. Also changed the directory from HellBase to HorseMenu because well this is HorseMenu.

### CODE REVIEW

**Review by Yimura — CHANGES_REQUESTED** [review]
You need to update the files under `.github/workflows` as they rely on the TemplateHellBase project and dll name.

**Comment by Rxann** [comment]
> You need to update the files under `.github/workflows` as they rely on the TemplateHellBase project and dll name.

I just looked in the files and it seems that everything is named HorseMenu properly? I have only worked with the workflows a couple of times so I could be missing something.

**Comment by Yimura** [comment]
Let's see if it works.

**Comment by Rxann** [comment]
> Let's see if it works.

It passed

**Comment by Rxann** [comment]
I moved the directory change the the pr that fixes the crashes so that why i updated the title

**Review by Yimura — APPROVED** [review]

**Pull request merged**
