### PR TITLE
Fix Failing Nightly CI

### LINKED ISSUE #141: [Bug]: Nightly CI Failing
### Describe the bug

Nightly CI fails to build.

### Steps To Reproduce

N/A

### Expected Behavior

To Build

### Logs and/or screenshots

N/A

### Store

Steam

### Language

English

### Additional context

@MarkEcza @DayibBaba  any ideas on what this could be? It builds just fine on my pc.

### Build

- [X] I've confirmed the issue exists on the latest version of HorseMenu

### PR DESCRIPTION
**Pull request by Rxann**
Reverts YimMenu/HorseMenu#79 (this should fix the nightly ci from what i see. the logs of the CI show that it can't open features.hpp which is not actually a file and this pr that is being reverted adds that.)

closes #141

@DayibBaba or @MarkEcza (sorry for second ping I just thought this is urgent enough)

### CODE REVIEW

**Comment by MarkEcza** [comment]
May i ask why you have deleted an entire submenu?

**Comment by Rxann** [comment]
> May i ask why you have deleted an entire submenu?

It reverts the faulty pr, which contains faulty includes. My github is also fucked so I can't pull the updated file.

**Comment by Rxann** [comment]
@MarkEcza can you run the ci as well to make sure this fixes the issue?

**Comment by Rxann** [comment]
@MarkEcza Can we merge this then i will properly reconstruct the code this is reverting.

**Comment by MarkEcza** [comment]
Closed by #143

**Pull request closed without merging**
