### PR TITLE
Update ClearCrimes.cpp

### PR DESCRIPTION
**Pull request by Deadlineem**
Test - working on bounty/crime removal, found some natives that could possibly fix this, i just cant figure out how to compile this sooo

This may also be of use

PLAYER::CLEAR_PLAYER_WANTED_LEVEL(guid);

### CODE REVIEW

**Comment by Rxann** [comment]
Do you have cmake and msvc installed on ur pc? also you should probably make this a draft pr

**Comment by Deadlineem** [comment]
> Do you have cmake and msvc installed on ur pc? also you should probably make this a draft pr

I installed vs22 and the issue im having is when i try to compile, it errors with 2 messages.  

Screenshot_10

**Review by Yimura — APPROVED** [review]

**Comment by Yimura** [comment]
@Deadlineem do you have `git` installed on your PC?

**Comment by Deadlineem** [comment]
> @Deadlineem do you have `git` installed on your PC? That might be the issue with your project not setting up properly.

No but i will install git when i get home from work and get back to you on this asap @Yimura.

**Comment by Deadlineem** [comment]
> @Deadlineem do you have `git` installed on your PC? That might be the issue with your project not setting up properly.

I got it to compile, but the game had a small update and now it crashes :(

**Comment by Deadlineem** [comment]
> Do you have cmake and msvc installed on ur pc? also you should probably make this a draft pr

BOUNTY::_BOUNTY_REQUEST_PAY_OFF_BOUNTY(guid); -- Pays the bounty price from your wallet, fairly legit // Does not remove currently active police

**Comment by Deadlineem** [comment]
@Yimura @Rxann 

Updated this severely, first crack at something in C++ by myself, the commit now changes ClearCrimes.cpp to pay off bounties from your wallet balance (instead of doing nothing like before)

Adds NeverWanted.cpp which sets the wanted mode to 0 or 1 (disabled/enabled)

Adds the Never Wanted toggle to the Self tab.

**Comment by Deadlineem** [comment]
> _BOUNTY_REQUEST_SERVED_FULL_JAIL_SENTENCE seemed to work fine, why change it? It removes your bounty for the current region you're in, unless this was changed in this last update. Have you tried _BOUNTY_REQUEST_SELF_REPORT_KILLED_BY_BOUNTY_HUNTER or _SET_BOUNTY_HUNTER_PURSUIT_CLEARED?

I used it right before the recent update, it didnt seem to work at all for me.  However, having pay bounties is a more "legit" way of doing it, and also having "Never Wanted" helps alot.

**Review by Yimura — APPROVED** [review]

**Pull request merged**
