### PR TITLE
Fix duplicate

### PR DESCRIPTION
**Pull request by MarkEcza**
I don't know how we managed to add a duplicate file. I don't have RDR currently installed can anyone check if everything's fine UI wise?

### CODE REVIEW

**Comment by MarkEcza** [comment]
@Rxann

**Comment by Rxann** [comment]
I will check in a few hours

**Comment by Rxann** [comment]
conflicts with #142?

**Comment by Rxann** [comment]
@MarkEcza This works well and is fine to merge. Should I close #142 ? I think this is the better PR.

**Comment by MarkEcza** [comment]
Thanks @Rxann .

**Comment by Rxann** [comment]
> Thanks @Rxann . 

Anytime

**Pull request merged**
