### PR TITLE
Protections, Updates, and More

### LINKED ISSUE #50: Fix Exodus crashes
Exodus is rare but it's still a good idea to fix their crashes

### LINKED ISSUE #118: [Bug] Max/Min Honor

### PR DESCRIPTION
**Pull request by Rxann**
Bumped to current ImGui version
Call Hooks
Voice Chat Spoofing
New Protections
Log Backups
Blip Spoofing
General Optimizations
General Improvements
Updated Net Events list from @AAA-ALR 
and More

closes #50 
closes #118

### CODE REVIEW

**Comment by AAA-ALR** [comment]
```
case "CProjectileCreationNode"_J:
{
	auto& data = node->GetData<CProjectileCreationData>();
	if (!WEAPON::IS_WEAPON_VALID(data.m_WeaponHash))
	{
		SyncCrashBlocked("invalid projectile weapon crash");
		return true;
	}
	break;
}
```
this crash was fixed in the last rockstar update

**Comment by Rxann** [comment]
> this crash was fixed in the last rockstar update

Ah okay, I will remove it. Thanks.

**Comment by Rxann** [comment]
> this crash was fixed in the last rockstar update

It still exists

**Comment by Rxann** [comment]
Jamison used it on me and some others so I reversed the crash subroutine and found a nullptr dereference.

**Pull request merged**
