### PR TITLE
Working invoker & natives.hpp

### PR DESCRIPTION
**Pull request by DayibBaba**
Natives.hpp is generated from [Natives Reference](https://rdr.gta.menu/natives).
Practically a port over from YimMenu, only difference being the fact we no longer need maps due to the game offering a function that provides the address upon giving it a natives hash.

It appears the vector3 needs a fix.

### CODE REVIEW

**Comment by Hydra-Source** [comment]
Looks good to me except the issue you stated. Haven't tested yet but there should definitely be a cache which gets inserted when the native is called the first time. Then it can be retrieved from the cache. If the vector3 isn't working yet you can mark it as a draft for now.

**Comment by xiaoxiao921** [comment]
All the issues you are describing are already fixed by maybegreat pr, this can be closed

**Comment by DayibBaba** [comment]
> All the issues you are describing are already fixed by maybegreat pr, this can be closed

Will close once #11 is merged.

**Comment by DayibBaba** [comment]
This PR is being dismissed in favor of #11

**Pull request closed without merging**
